config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#index'

  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  RATINGS = {
    '1 star': '⭐️',
    '2 stars': '⭐️⭐️',
    '3 stars': '⭐️⭐️⭐️',
    '4 stars': '⭐️⭐️⭐️⭐️',
    '5 stars': '⭐️⭐️⭐️⭐️⭐️'
  }

  def send_comment_email
    NotificationMailer.comment_added(self).deliver
  end
end

def rating
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :place
  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :photos

  geocoded_by :address
  after_validation :geocode

  validates :name, presence: true, length: { minimum: 3 }
  validates :address, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params)
    redirect_to place_path(@place)
  end

  private

  def photo_params
    params.require(:photo).permit(:picture, :caption, :place_id)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @places = Place.all.paginate(page: params[:page], per_page: 5)
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render text: 'Sorry, governor! You do not have access to edit this pub. 😔', status: :forbidden
    end
  end

  def update
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render text: 'Sorry, governor! You do not have access to update this pub. 😔', status: :forbidden
    end

    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render text: 'Sorry, governor! You do not have acess to delete this pub. 😔', status: :forbidden
    end

    @place.destroy
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Frosty Governor</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    </head>

    <body>
        <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <%= link_to 'Frosty Governor🍻', root_path, class: 'navbar-brand' %>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto mt-2 mt-md-0">
                    <li class="nav-item">
                        <%= link_to new_place_path, class: 'nav-link' do %>
                            <i class="fa fa-plus-circle"></i>
                            New Pub
                        <% end %>
                    </li>
                </ul>

                <ul class="navbar-nav">
                    <% if user_signed_in? %>
                        <li class="nav-item">
                          <%= link_to user_path(current_user), class: 'nav-link' do %>
                              <i class="fa fa-user-circle"></i>
                              My Profile
                          <% end %>
                        </li>
                        <li class="nav-item">
                            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
                                <i class="fa fa-sign-out"></i>
                                Sign out
                            <% end %>
                        </li>
                    <% else %>
                        <li class="nav-item">
                            <%= link_to new_user_session_path, class: 'nav-link' do %>
                                <i class="fa fa-sign-in"></i>
                                Sign in
                            <% end %>
                        </li>
                        <li class="nav-item">
                            <%= link_to new_user_registration_path, class: 'nav-link' do %>
                                🍺
                                <!-- <i class="fa fa-user-plus"></i> -->
                                Sign up
                            <% end %>
                        </li>
                    <% end %>
                </ul>
            </div>
        </nav>

            <% if notice.present? %>
                <p class="alert alert-info"><%= notice %></p>
            <% end %>
            <% if alert.present? %>
                <p class="alert alert-danger"><%= alert %></p>
            <% end %>

        <%= yield %>
    </body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box new-box col-6">
  <h2 class="new-place">Edit Your Pub:</h2>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name, label: 'Name:' %>
    <%= f.input :address, label: 'Address:' %>
    <%= f.input :description, label: 'Description:' %>
    <br>
    <%= f.submit 'Update Pub 🍻', class: 'btn btn-secondary btn-new' %>
  <% end %>
</div>

app/views/places/index.html.erb
<!-- homepage slider -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'pub3.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <!-- <h3>The Best Pubs for a Pint in London</h3> -->
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'pub1.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <!-- <h3>Underground and Hidden Pubs</h3> -->
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'pub4.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <!-- <h3>The Best Pubs - Nothing Else</h3> -->
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<br>
<h1 class="text-center">Underground Pubs in London🍻</h1>
<br>

<% @places.each do |place| %>
  <div class="booyah-box col-8">
    <% if place.photos.present? %>
      <div class="col-12">
        <%= image_tag place.photos.last.picture, class: 'img-fluid img-index float-right' %>
      </div>
    <% end %>

    <h2><%= link_to place.name, place_path(place) %>🍻</h2>
    <i class="italic"><%= place.address %></i><br><br>
    <p class="description"><%= place.description %></p>
    <br class="clear">

    <!-- <% if place.photos.present? %>
      <div class="col-12">
        <%= image_tag place.photos.last.picture, class: 'img-fluid img-index float-right' %>
      </div>
    <% end %> -->


    <% if place.comments.present? %>
      <div class="col-12">
        <blockquote class="index">
          <% if place.comments.last.rating.present? %>
            <%= place.comments.last.rating %>
          <% end %>
          “<%= place.comments.last.message %>”
          <!-- <small><%= place.comments.last.user.email %></small> -->
        </blockquote>
      </div>
    <% end %>


    <% if place.user.present? %>
      <small class="float-right">Added by <%= place.user.email %> 🇬🇧</small>
    <% end %>
  </div>
<% end %>

<div class="col-12">
  <%= will_paginate @places, renderer: BootstrapPagination::Rails, page_links: false  %>
</div>

app/views/places/new.html.erb
<div class="booyah-box new-box col-6">
  <h2 class="new-place">Enter Your Pub Details:</h2>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name, label: 'Name:' %>
    <%= f.input :address, label: 'Address:' %>
    <%= f.input :description, label: 'Description:' %>
    <br>
    <%= f.submit 'Add Pub 🍻', class: 'btn btn-secondary btn-new' %>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-8 well clearfix">
  <h2><%= @place.name %>🍻 <%= link_to root_path, title: 'Close' do %>
      <i class="fa fa-window-close float-right"></i>
  <% end %>
  </h2>
  <i class="italic"><%= @place.address %></i>
  <br><br>
  <p class="description"><%= @place.description %></p>
  <br>
  <% if @place.latitude.present? && @place.longitude.present? %>
    <script>
      function initMap() {
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello, Governor!'
        });
      }
    </script>

    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA6CT4RvWoDdlVLO7F_bD52pVGuR0U-Ax8&callback=initMap">
    </script>

    <div id="map"></div>
  <% end %>
  <br>
  <div class="float-right">
    <% if current_user && current_user == @place.user %>
      <%= link_to 'Edit ✍️', edit_place_path(@place), class: 'btn btn-secondary' %>
      <%= link_to 'Delete', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
    <% end %>
  </div>

  <!-- Button trigger modal photos-->
  <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#myPhotoModal">
    Add a Photo 📷
  </button>

  <!-- Modal -->
  <div class="modal fade" id="myPhotoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button> -->
          <h4 class="modal-title" id="myModalLabel">Add a Photo:</h4>
        </div>

          <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
            <div class="modal-body">
              <%= f.input :picture, label: 'Picture:' %>
              <%= f.input :caption, label: 'Caption:' %>
            </div>
            <div class="modal-footer">
              <%= f.submit "Add Photo 📷", class: 'btn btn-secondary' %>
              <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
          <% end %>
      </div>
    </div>
  </div>

  <!-- Button trigger modal comments-->
  <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#myModal">
    Add a Comment 💬
  </button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button> -->
          <h4 class="modal-title" id="myModalLabel">Add a Comment:</h4>
        </div>

          <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
            <div class="modal-body">
              <%= f.input :message, label: 'Comment:' %>
              <%= f.input :rating, as: :select, collection: Comment::RATINGS, label: 'Rating:' %>
            </div>
            <div class="modal-footer">
              <%= f.submit "Add Comment 💬", class: 'btn btn-secondary' %>
              <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
          <% end %>
      </div>
    </div>
  </div>

    <br>
    <br>
    <br>
    <h2>Photos 📷</h2>

    <div class="row">
      <% @place.photos.each do |photo| %>
        <div class="col-12 col-sm-6">
          <%= image_tag photo.picture, :class => 'img-fluid' %>
          <%= photo.caption %>
        </div>
      <% end %>
    </div>

    <br>
    <br>
    <br>
    <h2>Comments 💬</h2>
    <br>
    <div class="row">
      <% @place.comments.each do |comment| %>
        <div class="col-12 col-sm-6">
          <blockquote>
            <strong><%= comment.rating %></strong>
              “<%= comment.message %>”
            <small class="italic"><%= comment.user.email %></small>
          </blockquote>
        </div>
      <% end %>
    </div>
</div> <!-- .booyah-box -->

app/views/users/show.html.erb
<div class="booyah-box col-8">
  <div class="row">
    <div class="col-4">
      <%= image_tag 'user.png', class: 'user'%>
    </div>

    <div class="col-8">
      <h3><%= @user.email %></h3>
      <h3>Member since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
      <h4><%= @user.comments.count %> total comments</h4>
      <h4><%= @user.comments.where(rating: '5_stars').count %> total 5 star reviews</h4>
    </div>
  </div>

  <br>
  <br>
  <br>
  <h2 class="text-center">Comments 💬</h2>
  <br>
  <br>
  <div class="row">
    <% @user.comments.each do |comment| %>
      <div class="col-12 col-sm-6">
        <h5 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h5>
        <blockquote>
          <strong><%= comment.rating %></strong>
            “<%= comment.message %>”
          <small class="italic"><%= comment.user.email %></small>
        </blockquote>
      </div>
    <% end %>
  </div>

  <br>
  <br>
  <h2 class="text-center">Places 🍻</h2>
  <br>
  <br>
  <div class="row">
    <% @user.places.each do |place| %>
      <div class="col-12 col-sm-6">
        <% if place.photos.present? %>
          <div class="col-12">
            <%= image_tag place.photos.last.picture, class: 'img-fluid img-index float-right' %>
          </div>
        <% end %>

        <h2><%= link_to place.name, place_path(place) %>🍻</h2>
        <i class="italic"><%= place.address %></i><br><br>
        <p class="description"><%= place.description %></p>
        <br class="clear">

        <% if place.comments.present? %>
          <div class="col-12">
            <blockquote class="index">
              <% if place.comments.last.rating.present? %>
                <%= place.comments.last.rating %>
              <% end %>
              “<%= place.comments.last.message %>”
              <!-- <small><%= place.comments.last.user.email %></small> -->
            </blockquote>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>